---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: create ami 
    ec2_ami: 
      region: us-east-1
      instance_id: i-0f0126465ae7a108b
      wait: no
      name: new_ami2
      device_mapping: 
        - device_name: /dev/sdb1
          size: 8
          delete_on_termination: true
          volume_type: gp2

    register: instance

