---
- hosts: aws 
  remote_user: ec2-user
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: ls -la
    shell: ls -la
    register: result
  - name: show output
    debug: var=result
